---
- name: Install Apache2 and PHP and packages
  become: true
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: latest
    update_cache: true

- name: Copy Virtual Host file
  become: true
  ansible.builtin.copy:
    src: webserver.conf
    dest: /etc/apache2/sites-available

- name: Prioritise index.php over index.html
  become: true
  lineinfile:
      path: /etc/apache2/mods-enabled/dir.conf
      regexp: '^(.*)DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm(.*)$'
      line: 'DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
      backrefs: yes
  
- name: Enable new site
  become: true
  ansible.builtin.command: a2ensite webserver

- name: Disable default site
  become: true
  ansible.builtin.command: a2dissite 000-default 

- name: Create /var/repos
  become: true
  ansible.builtin.file:
    path: /var/repos
    state: directory

- name: Clone the MyWebProject Repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/khalford/MyWebProject.git
    dest: /var/repos/MyWebProject
    single_branch: yes
    version: main

- name: Copy git files to site
  become: true
  ansible.builtin.copy:
    src: /var/repos/MyWebProject/
    dest: /var/www
    remote_src: true

- name: Reload Apache2 Service
  become: true
  command: systemctl reload apache2.service

- name: Copy index.php to site
  become: true
  copy:
    src: index.php
    dest: /var/www/MyWebProject
